// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDncBy05ZKSTDXoWuqDH9Frt2uAIwbLdBU',
    appId: '1:868752159918:web:f55aaeb9bda3174c35a93f',
    messagingSenderId: '868752159918',
    projectId: 'foodtracker-da092',
    authDomain: 'foodtracker-da092.firebaseapp.com',
    storageBucket: 'foodtracker-da092.firebasestorage.app',
    measurementId: 'G-RR21FG7M5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIk4hExAtq8GeqQ6E8OTjhAWUuTOKqGc',
    appId: '1:868752159918:android:9e7802142f4ae39535a93f',
    messagingSenderId: '868752159918',
    projectId: 'foodtracker-da092',
    storageBucket: 'foodtracker-da092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEIXeXixv535hg4uBscZkbe5VZMD8Hos4',
    appId: '1:868752159918:ios:c974a623c64a1be035a93f',
    messagingSenderId: '868752159918',
    projectId: 'foodtracker-da092',
    storageBucket: 'foodtracker-da092.firebasestorage.app',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEIXeXixv535hg4uBscZkbe5VZMD8Hos4',
    appId: '1:868752159918:ios:c974a623c64a1be035a93f',
    messagingSenderId: '868752159918',
    projectId: 'foodtracker-da092',
    storageBucket: 'foodtracker-da092.firebasestorage.app',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDncBy05ZKSTDXoWuqDH9Frt2uAIwbLdBU',
    appId: '1:868752159918:web:c9b7af88c83e74c135a93f',
    messagingSenderId: '868752159918',
    projectId: 'foodtracker-da092',
    authDomain: 'foodtracker-da092.firebaseapp.com',
    storageBucket: 'foodtracker-da092.firebasestorage.app',
    measurementId: 'G-YWP0QC2YXH',
  );
}
